export const ERROR_DISPLAY_ON = "ERROR_DISPLAY_ON"
export const ERROR_DISPLAY_OFF = "ERROR_DISPLAY_OFF"
export const ITEMS_LOAD = "ITEMS_LOAD"
export const ADD_TO_CARD = "ADD_TO_CARD"
export const DELETE_IN_CARD = "DELETE_IN_CARD"
export const USER_IS_AUTH = "USER_IS_AUTH"
export const USER_IS_AUTH_ADMIN = "USER_IS_AUTH_ADMIN"
export const USER_LOG_OUT = "USER_IS_AUTH_LOG_OUT"
export const USER_ADMIN_LOG_OUT = "USER_IS_AUTH_ADMIN_LOG_OUT"
export const CREAT_ORDER = "CREAT_ORDER"
export const DELETE_ORDER = "DELETE_ORDER"
export const CREAT_CONTACT = "CREAT_CONTACT"
export const POSTS_LOAD = "POSTS_LOAD"
export const REGISTER_DATA = "REGISTER_DATA"
export const CREAT_ITEM_HISTORY = "CREAT_ITEM_HISTORY"
export const LEVEL_UP = "LEVEL_UP"
export const GET_EXPERIENCE_TEN_POINT = "GET_EXPERIENCE_TEN_POINT"
export const GET_EXPERIENCE_FIFTIETH_POINT = "GET_EXPERIENCE_FIFTIETH_POINT"
export const RESET_EXPERIENCE = "RESET_EXPERIENCE"









